name: Build PHP (Windows)

on:
  workflow_dispatch:
    inputs:
      php-version:
        description: 'PHP version (e.g. 8.4)'
        required: true
        default: '8.4'
      extensions:
        description: 'Comma-separated extensions (e.g. intl,mbstring,curl,exif,opcache)'
        required: false
        default: 'intl,mbstring,curl,exif,opcache,zip,xml'
      ini-values:
        description: 'Comma-separated ini values (e.g. memory_limit=512M,display_errors=1)'
        required: false
        default: 'memory_limit=512M,display_errors=1,error_reporting=E_ALL,post_max_size=64M,upload_max_filesize=64M,max_execution_time=120,opcache.enable=1,opcache.memory_consumption=128,opcache.interned_strings_buffer=8,opcache.max_accelerated_files=4000,opcache.revalidate_freq=0,opcache.enable_cli=1'

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ github.event.inputs.php-version }}
          extensions: ${{ github.event.inputs.extensions }}
          ini-values: ${{ github.event.inputs.ini-values }}
          tools: composer

      - name: Show PHP info
        shell: pwsh
        run: |
          php -v
          php -m
          php --ini

      # Ensure OPCache section present (append if missing) — helps when setup-php doesn't write all opcache keys
      - name: Ensure opcache config appended to php.ini
        if: always()
        shell: pwsh
        run: |
          $loaded = php --ini | Select-String 'Loaded Configuration File' | ForEach-Object { $_.ToString() -replace '.*:\s*','' }
          if (-not $loaded -or $loaded -eq '(none)') {
            Write-Host "No loaded php.ini found, skipping manual opcache append."
            exit 0
          }
          $iniPath = $loaded.Trim()
          Write-Host "Using php.ini: $iniPath"
          $opcfg = @"
          [opcache]
          opcache.enable=1
          opcache.memory_consumption=128
          opcache.interned_strings_buffer=8
          opcache.max_accelerated_files=4000
          opcache.revalidate_freq=0
          opcache.enable_cli=1
          "@
          # Append only if section not present
          $content = Get-Content -Raw -ErrorAction SilentlyContinue $iniPath
          if ($content -notmatch '\[opcache\]') {
            Add-Content -Path $iniPath -Value $opcfg
            Write-Host "Appended opcache settings to php.ini"
          } else {
            Write-Host "opcache section already exists — skipping append"
          }

      - name: Install composer deps
        run: composer install --no-progress --prefer-dist

      - name: Run tests (example)
        run: vendor/bin/phpunit --colors --stop-on-failure || exit 0
