name: Build PHP

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
  SPC_VERSION: 2.7.5

jobs:
  build:
    name: "8.4" 
    runs-on: "windows-latest"
